### ISSUE TITLE
Image sizing/cropping

### ISSUE THREAD

**Issue by seanwash** [WatchNature/watchnature-nuxt#13]
@seanwash commented on [Fri Aug 04 2017](https://github.com/WatchNature/watchnature-app/issues/43)

Any thoughts @bradyswenson? Do we want to stick to an aspect ratio, or do we just want to enforce max width/height?

**Comment by bradyswenson** [comment]
we want to allow for images 16:9 wide and tall ... those ratios should be the max min pixels

That should be a good start

**Comment by seanwash** [comment]
resolved IRL via Slack. Opted for square photos for the stream for now.
